---
- name: run the facts machine
  hosts: "{{ hosts | default('all') | lower }}"
  gather_facts: yes
  #connection: "{{ ansible_connection | default() }}"

  roles:
    - role: facts_machine

  tasks:
    - debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution_major_version }} {{ ansible_distribution_major_version }}"

  #- name: print ansible facts
  #  debug:
  #    var: ansible_facts

  #- name: print hostvars
  #  debug:
  #    var: hostvars
  
