---
- name: Oosto v1 to v2 install
  hosts: all
  gather_facts: True
  tasks:

<<<<<<< HEAD
    #    - name: Create Oosto backup or v1 data
    #  include_role:
    #    name: export_data

    - name: Convert workstation to server and update to latest RHEL 7
      include_role:
        name: wk2server
          #when: (ansible_kernel != '3.10.0-1160.90.1.el7.x86_64' and oostoo_back.stat.exists)
          #when: oosto_backup.stat.exists and ansible_kernel != '3.10.0-1160.90.1.el7.x86_64'
=======
    - name: Convert workstation to server and update to latest RHEL 7
      include_role:
        name: wk2server
      when: ansible_kernel != '3.10.0-1160.90.1.el7.x86_64'
>>>>>>> c76729024ff2bdf0a14ed790de01b662c5c3a11e

    - name: Upgrade server from RHEL 7 to RHEL 8
      include_role:
        name: prep4rhel8
      when: kernel_version.stdout == '3.10.0-1160.90.1.el7.x86_64'

<<<<<<< HEAD
        #    - name: Clean up of old files
        #include_role:
        #name: cleanup
        #when: kernel_version.stdout == '4.18.0-305.25.1.el8_4.x86_64'
=======
    - name: Clean up of old files
      include_role:
        name: cleanup
      when: kernel_version.stdout == '4.18.0-305.25.1.el8_4.x86_64'
>>>>>>> c76729024ff2bdf0a14ed790de01b662c5c3a11e
