---
 
- name: Copy migration tar to server
  copy:
    src: migration-v1-to-v2-1.0.5.tar.gz
    dest: /tmp
    mode: 755
 
- name: extract migration tar file
  unarchive:
    src: /tmp/migration-v1-to-v2-1.0.5.tar.gz
    dest: /opt
    remote_src: yes
 
      #- name: Run migration
  #command: /opt/migration-v1-to-v2-1.0.5/migration-tool.sh --action export
 
    #- name: get status
  #shell: kubectl logs -f $(kubectl get pods | grep migration | awk '{print $1}')
  #register: k8_log
 
- name: Tar folder for migration
  archive:
    path: /tmp
    dest: /storage/v1_exports.tar.gz
    format: gz
      #  when: '"successful" in k8_log.stdout'
      
- name: Verify backup file exists
  stat:
    path: /storage/v1_exports.tar.gz 
  register: oosto_backup
