---
- name: copy rpm package to client
  copy:
     src: redhat-release-server-7.9-6.el7_9.x86_64.rpm
     dest: /tmp
     mode: 0755

- name: install the server rpm
  command: rpm -ivh --force /tmp/redhat-release-server-7.9-6.el7_9.x86_64.rpm
  ignore_errors: True

- name: remove workstation packages
  yum:
    name: redhat-release-workstation*  
    state: absent

- name: clear the pem file
  file:
    path: /etc/pki/product/71.pem
    state: absent 

- name: clean yum
  command: yum clean all
  ignore_errors: True

- name: Remove workstation repo
  ansible.builtin.yum_repository:
    name: rhel-7-workstation-rpms
    file: redhat
    state: absent


      #- name: remove workstation repos
      # command: subscription-manager repos --disable=rhel-7-workstation-rpms
      #ignore_errors: True

- name: run distro-sync
  command: yum -y distro-sync

- name: Update all packages
  yum:
    name: '*'
    state: latest
