---
# This play will take any 'ansible_network_os' value and run the corresponding tasks
- name: "fact checking {{ ansible_network_os }} hosts"
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_network_os }}.yml"
      skip: true
      paths: tasks

