---

- name:
  ansible.builtin.yum:
    name: leapp-upgrade
    enablerepo: rhel-7-server-extras-rpms

- name: remove not needed modules
  modprobe:
    name: "{{item}}"
    state: absent
  with_items:
     - "pata_acpi"
     - "floppy"

- name: Remove kernel devel pkgs
  yum:
    name: kernel-devel-3.10.0-957.27.2.el7
    state: absent

- name: Remove symlink
  file:
    path: ssd
    state: absent

- name: Run pre leapp
  command: leapp preupgrade --target 8.4
  ignore_errors: True

- name: add leapp answers
  command: leapp answer --section remove_pam_pkcs11_module_check.confirm=True

- name: Run pre leapp
  command: leapp upgrade --target 8.4

- name: reboot the server
  reboot:

- name: Wait for server to complete the upgrade
  wait_for_connection:
    delay: 900
    timeout: 7200

- name: Kernel updated!
  fail:
    msg: Kernel is not updated {{ kernel_version.stdout }}
  when: (kernel_verion.stdout != '4.18.0-305.25.1.el8_4.x86_64')


